<?php
/** @var umiTemplaterPHP|BaseExtension|PageExtension|UmiSettingsExtension $this */
/** @var array $variables */
$page = $this->getPage();

$title = trim($page->getValue(SiteContentPagePaymentModel::field_bottom_title));
$content = trim($page->getValue(SiteContentPagePaymentModel::field_bottom_content));
if($title || $content):?>
    <section class="page-main__text-block text-block">
        <?php if($title):?>
            <h2 class="text-block__heading"><?php echo $title;?></h2>
        <?php endif;?>

        <?php if($content):?>
            <div class="text-block__text text-block__text_mission">
                <?php echo $this->parseTplMacros($content, $page->getId());?>
            </div>
        <?php endif;?>
    </section>
<?php endif;?>