<?php
/** @var umiTemplaterPHP|BaseExtension|PageExtension|UmiSettingsExtension $this */
/** @var array $variables */
$page = $this->getPage();
$h1 = trim($page->getValue('h1'));

$mapImage = $page->getValue(SiteContentPageContactsModel::field_map_image);

$image = $page->getValue(SiteContentPageContactsModel::field_image);
$address = trim($page->getValue(SiteContentPageContactsModel::field_address));
$workingTime = trim($page->getValue(SiteContentPageContactsModel::field_working_time));

$contactsPhone = $this->getCommonVar(OlympicTouchExtension::common_var_contacts_phone);
$contactsEmail = $this->getCommonVar(OlympicTouchExtension::common_var_contacts_email);

$feedbackPageLink = false;
$feedbackPage = getArrayKey($this->getUmiSettingsValue(SiteUmiSettingsOlympicTouchModel::field_system_feedback_page_id), 0);
if($feedbackPage instanceof umiHierarchyElement) {
    $feedbackPageLink = $this->getPageLink($feedbackPage->getId());
}

$requisitesPageLink = false;
$requisitesPage = getArrayKey($this->getUmiSettingsValue(SiteUmiSettingsOlympicTouchModel::field_system_requisites_page_id), 0);
if($requisitesPage instanceof umiHierarchyElement) {
    $requisitesPageLink = $this->getPageLink($requisitesPage->getId());
}
?>
<header class="page-main__header main-header">
    <?php echo $this->render(null, OlympicTouchExtension::assets_breadcrumbs);?>

    <?php if($h1):?>
        <h1 class="main-header__heading"><?php echo $h1;?></h1>
    <?php endif;?>
</header>

<section class="page-main__section contact-info">
    <?php if($mapImage instanceof umiImageFile && !$mapImage->getIsBroken()):?>
        <h2 class="visually-hidden">Карта</h2>
        <div class="contact-info__map" style="background-image: url('<?php echo $mapImage->getFilePath(true);?>');"></div>
    <?php endif;?>

    <div class="page-main__container">
        <div class="flex-grid">
            <?php if($image instanceof umiImageFile && !$image->getIsBroken()):?>
                <div class="flex-grid__column flex-grid__column_12 flex-grid__column_medium_6 flex-grid__column_large_5">
                    <img src="<?php echo $this->makeThumbnailFull($image->getFilePath(true), 460);?>" width="460" class="contact-info__img" alt="<?php echo $image->getAlt();?>" />
                </div>
            <?php endif;?>

            <div class="contact-info__details flex-grid__column">
                <h2 class="visually-hidden">Контактная информация</h2>
                <?php if($address || $workingTime):?>
                    <address class="contact-info__address address">
                        <?php if($address):?>
                            <p class="address__place"><?php echo $address;?></p>
                        <?php endif;?>
                        <?php if($workingTime):?>
                            <p class="address__time">
                                Время работы:<br />
                                <?php echo nl2br($workingTime);?>
                            </p>
                        <?php endif;?>
                    </address>
                <?php endif;?>

                <?php if($contactsPhone || $contactsEmail):?>
                    <ul class="contact-info__contacts contacts">
                        <?php if($contactsPhone):?>
                            <li class="contacts__item">
                                <a href="tel:<?php echo $this->preparePhoneLink($contactsPhone);?>" class="contacts__link"><?php echo $contactsPhone;?></a>
                            </li>
                        <?php endif;?>
                        <?php if($contactsEmail):?>
                            <li class="contacts__item">
                                <a href="mailto:<?php echo $contactsEmail;?>" class="contacts__link"><?php echo $contactsEmail;?></a>
                            </li>
                        <?php endif;?>
                    </ul>
                <?php endif;?>

                <?php if($feedbackPageLink || $requisitesPageLink):?>
                    <div class="contact-info__buttons">
                        <?php if($feedbackPageLink):?>
                            <a href="<?php echo $feedbackPageLink;?>" class="button">Написать нам</a>
                        <?php endif;?>
                        <?php if($requisitesPageLink):?>
                            <a href="<?php echo $requisitesPageLink;?>" class="button button_gray">Наши реквизиты</a>
                        <?php endif;?>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </div>
</section>