<?php
/** @var umiTemplaterPHP|BaseExtension|PageExtension|UmiSettingsExtension $this */
/** @var array $variables */
$page = $this->getPage();
$h1 = trim($page->getValue('h1'));
$parentId = $page->getParentId();

try {
    $resultFiles = $this->macros(
        'filemanager',
        'getFileManagerPageFiles',
        array(
            'pageId' => $page->getId(),
        )
    );
} catch (Exception $e) {
    $resultFiles = false;
}
?>
<header class="page-main__header main-header">
    <?php echo $this->render(null, OlympicTouchExtension::assets_breadcrumbs);?>

    <?php if($h1):?>
        <h1 class="main-header__heading"><?php echo $h1;?></h1>
    <?php endif;?>

    <?php echo $this->render(array(
        OlympicTouchExtension::assets_sub_menu_param_page_id => $parentId ? $parentId : $page->getId()
    ), OlympicTouchExtension::assets_sub_menu);?>
</header>

<section class="page-main__section">
    <div class="page-main__container">
        <?php if(is_array($resultFiles) && isset($resultFiles['items'])):?>
            <h2 class="visually-hidden">Загрузите информацию:</h2>

            <ul class="files">
                <?php foreach($resultFiles['items'] as $item):?>
                    <li class="files__item">
                        <a href="<?php echo $item['file'];?>" class="files__link"><?php echo $item['name'];?></a>
                    </li>
                <?php endforeach;?>
            </ul>
        <?php endif;?>
    </div>
</section>