<?php
/** @var umiTemplaterPHP|BaseExtension|PageExtension|UmiSettingsExtension $this */
/** @var array $variables */
$page = $this->getPage();
$h1 = trim($page->getValue('h1'));
?>
<header class="page-main__header main-header">
    <?php echo $this->render(null, OlympicTouchExtension::assets_breadcrumbs);?>

    <?php if($h1):?>
        <h1 class="main-header__heading"><?php echo $h1;?></h1>
    <?php endif;?>

    <?php echo $this->render(array(
        OlympicTouchExtension::assets_sub_menu_param_page_id => $page->getParentId()
    ), OlympicTouchExtension::assets_sub_menu);?>
</header>

<section class="page-main__section">
    <div class="page-main__container">
        <div class="flex-grid flex-grid_large_2">
            <?php echo $this->render(null, 'layouts/default/modules/content/content/payment/left');?>

            <?php echo $this->render(null, 'layouts/default/modules/content/content/payment/right');?>
        </div>

        <?php echo $this->render(null, 'layouts/default/modules/content/content/payment/bottom');?>
    </div>
</section>
