<?php
/** @var umiTemplaterPHP|BaseExtension|PbExtension|UmiSettingsExtension $this */
/** @var array $variables */

$contactsList = $this->render(null, PbExtension::assets_contacts_list);
?>
<header class="page-main__header main-header">
    <?php echo $this->render(array(
        OlympicTouchExtension::assets_breadcrumbs_param_last => 'Сообщение отправлено'
    ), OlympicTouchExtension::assets_breadcrumbs);?>

    <h1 class="main-header__heading">Сообщение успешно отправлено</h1>
</header>

<section class="page-main__section">
    <div class="page-main__container">
        <div class="response response_success">
            <p class="response__text">Мы&nbsp;свяжемся с&nbsp;вами в&nbsp;ближайшее время для уточнения деталей оформления карты.</p>
            <p class="response__comment">Вы&nbsp;также можете связаться с&nbsp;нами любым из&nbsp;доступных способов:</p>
            <ul class="response__contacts contacts">
                <li class="contacts__item">
                    <a href="tel:89210984646" class="contacts__link">8 921 098-46-46</a>
                </li>
                <li class="contacts__item">
                    <a href="mailto:info@olympic-touch.ru" class="contacts__link">info@olympic-touch.ru</a>
                </li>
            </ul>
            <a href="/" class="response__button button">Вернуться на&nbsp;главную</a>
        </div>
    </div>
</section>