<?php
/** @var umiTemplaterPHP|BaseExtension $this */
/** @var array $variables */

$templateResources = $this->getTemplateResources();
$templateVersion = $this->getTemplateVersion();

$title = $this->getSiteMetaTitle();
$description = $this->getSiteMetaDescription();
$keywords = $this->getSiteMetaKeywords();
?>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="ie=edge" />

<title><?php echo $title;?></title>
<meta name="description" content="<?php echo htmlspecialchars($description);?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($keywords);?>" />

<link rel="stylesheet" href="<?php echo $templateResources;?>/css/style.min.css" />
<link rel="icon" href="<?php echo $templateResources;?>/favicons/base-16x16.png" sizes="16x16" />
<link rel="icon" href="<?php echo $templateResources;?>/favicons/base-24x24.png" sizes="32x32" />
<link rel="icon" href="<?php echo $templateResources;?>/favicons/base-32x32.png" sizes="32x32" />
<link rel="icon" href="<?php echo $templateResources;?>/favicons/base-64x64.png" sizes="64x64" />

<!-- iOS -->
<meta name="apple-mobile-web-app-title" content="<?php echo $title;?>" />
<link rel="apple-touch-icon" sizes="120x120" href="<?php echo $templateResources;?>/img/favicons/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon" sizes="152x152" href="<?php echo $templateResources;?>/img/favicons/apple-touch-icon-152x152.png" />
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $templateResources;?>/img/favicons/apple-touch-icon-180x180.png" />
<!-- og -->
<meta property="og:title" content="<?php echo $title;?>" />
<meta property="og:description" content="<?php echo $description;?>" />
<meta property="og:image" content="<?php echo $templateResources;?>/favicons/og.jpg" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="Фитнес-клуб Olympic Touch" />

<meta property="og:url" content="<?php echo $this->getRequestUrl();?>" />

<meta property="og:locale" content="ru_RU" />